### ISSUE TITLE
AutoFixture AutoData tests not running

### ISSUE THREAD

**Issue by sm-g** [nunit/dotnet-test-nunit#105]
In VS2015 Test Explorer tests with `[Test, AutoData]` marked as not runned.

On build server `mstest` with `nunit3adapter` vsix runs them as expected.

project.json:
"NUnit": "3.6.0",
"NUnitLite": "3.6.0",
"dotnet-test-nunit": "3.4.0-beta-3",

**Comment by CharliePoole** [comment]
Is this intended as a report against the dotnet test adapter or the nunit 3 test adapter? You mentioned the problem earlier on a different adapter issue and I suggested you make a separate report. The json file does look like you are using dotnet test, so the adapter is likely irrelevant but I want to be sure so that the right people are looking at the problem.

What are you targeting with your tests?

**Comment by sm-g** [comment]
It was my fault, missed binding redirect for AutoFixture.Nunit (https://github.com/AutoFixture/AutoFixture/issues/754)
