### ISSUE TITLE
Passing options via dotnet test -- [additional arguments] doesn't work

### ISSUE THREAD

**Issue by bcuff** [nunit/dotnet-test-nunit#107]
Example:

```
> dotnet test -- "--timeout=30000"
...
NUnit .NET Core Runner 3.4.0
Copyright (C) 2016 Charlie Poole
Invalid argument: --timeout=30000
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
```

**Comment by rprouse** [comment]
Timeout does not currently work in the .NET Core/PCL build of the NUnit framework because the required threading libraries were not available when it was written. That will hopefully be rectified when we release the CSPROJ version of the .NET Core runner, but it will not be updated in this tool because this adapter will no longer work with VS 2017 or the new CSPROJ .NET Core tooling.
