### ISSUE TITLE
Can't install 3.4 Alpha under .NET 4.6.1

### ISSUE THREAD

**Issue by mhsimkin** [nunit/dotnet-test-nunit#36]
Most of the .NET Core Extensions classes can be installed under .NET 4.5+.  I'm using the new classes in under 4.6.1.  When I try to install the Alpha I get the following error message from the NuGet Package Manager:

```
Install-Package : Could not install package 'Microsoft.NETCore.Targets 1.0.1-rc2-24027'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain an
y assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  dotnet-test-nunit -Pre
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```
 
Will the 3.4 be supporting non .NET Core projects?

Thanks

**Comment by rprouse** [comment]
It should work, but there may be a mistake in the dependencies, I will test it.

In the meantime, are you using alpha 2? Can you post your `project.json`?

**Comment by mhsimkin** [comment]
My project is .NET 4.6.1.  I'm not using a project.json.

**Comment by rprouse** [comment]
If you are just using .NET 4.6.1, why not just use the full NUnit Framework and the console runner? Will the existing console runner fail if you import .NET Core Extensions?

Do you know if the other .NET Core runners (mstest and xunit) work like you are trying to use this?

**Comment by mhsimkin** [comment]
I might be a bit confused.  Does the full console runner support the Microsoft.Extensions.DependencyInjection.  Will I have an IServicesCollection that I can add my objects to?

Don't know about the other runners.

**Comment by rprouse** [comment]
I might be confused too, this is all pretty new and I am still learning :smile: 

I would assume that the dependency injection would work in the console runner if it works in your application. I don't know how it is hooked up under the covers, but the NUnit console is just another .NET application to run your tests under, so if everything gets wired up for your app, it should work.

To be honest, I wouldn't expect `dotnet-test-nunit` to work without a `project.json` file since the `dotnet` command line relies on the `project.json` to know which runner to spin up when you type `dotnet test`. If you want to use the `dotnet` CLI, I would expect that you need to convert your project to an `xproj/project.json` format and only target `net461`. I have one ASP.NET MVC 5 app that does this because I need the old Entity Framework 6 for spatial.

**Comment by mhsimkin** [comment]
Thanks.

I guess I'm going to have to do more digging/reading/researching.

Please consider this issue as resolved.

Thank you for all the help.

marc
