### ISSUE TITLE
TimeoutAttribute missing after using dotnet-test-nunit and 3.4.1

### ISSUE THREAD

**Issue by CharliePoole** [nunit/dotnet-test-nunit#47]
@danielwertheim commented on [Mon Jul 11 2016](https://github.com/nunit/nunit/issues/1658)

Upgrading/migrating to `dotnet-test-nunit` and 3.4.1 and then `TimeoutAttribute` was not found anymore.

**Comment by rprouse** [comment]
We should probably move this back to the main NUnit repo :smile: 

This is a known issue, `Timeout` was not included in the PCL (Portable) version of the framework because timing out a test requires threading and threads are not available in most PCL profiles. We are hoping to reintroduce as much of the lost functionality as possible in the next release by converting the PCL version of NUnit to a .NET Standard target.

**Comment by CharliePoole** [comment]
My mistake... I somewhere got the idea you were building your own version of the framework for this project... I'll comment on the other issue.
