### ISSUE TITLE
Adding "testRunner": "nunit" to project.json builds tests in structure than NUnit3.Console cannot run

### ISSUE THREAD

**Issue by generik0** [nunit/dotnet-test-nunit#92]
Hi

If i add "testRunner": "nunit" into a .net core class project it build the references libraries int into path:
\bin\Debug\net452\win7-x64 but the project class is in \bin\Debug\net452\.

This means MSBuild with a PS running NUnit3.Console cannot find the releated nuint.framework.dll for the build.

Why is the  "testRunner": "nunit" creating a sub os defined folder in the bin folder? e.g. "win7-x64" and is there any way to run the tests from both VS and a PS Script?

**Comment by rprouse** [comment]
Are you saying that when you don't have "testRunner": "nunit" in your project file, it doesn't build to the win7-x64 sub-directory? I would assume that it does no matter what because that is how .NET Core project JSON files work. The NUnit .NET Core adapter has nothing to do with this, it is all straight .NET Core. The adapter is only called when you run `dotnet test`.

Also, from the command line, you shouldn't be running your tests using the NUnit Console, but instead `dotnet test`. If you run `dotnet help test` you will see that you can specify the framework and runtime.

Of course, all of this changes once you switch to the CSPROJ/MSBuild format 😦 

I am going to close this as a question. Feel free to post if you need more info.

**Comment by generik0** [comment]
Hi Rob

Thanks for your reply.
Jeps, if i renove the test runner in project.json it does not build to win7x64.
I will try the dot net runner. Thanks!

BR Rik

You can clone and try for yourself if you don't beleive me... GitHub: Smooth.IoC.Dapper.Repository.UnitOfWork
